{{ config(materialized='view', alias='sessions') }}

SELECT
  fullVisitorId || '-' || visitStartTime as table_pkey,
  visitorId as visitor_id,
  visitNumber as visit_number,
  visitId as visit_id,
  visitStartTime as visit_start_time,
  date(cast(substr(date, 0, 4) as int64), cast(substr(date, 5, 2) as int64), cast(substr(date, 7) as int64)) as visit_date,
  totals.visits as visits,
  totals.hits as hits,
  totals.pageviews as page_views,
  totals.timeOnSite as time_on_site,
  totals.bounces as bounces,
  totals.transactions as transactions,
  totals.transactionRevenue as transaction_revenue,
  totals.newVisits as new_visits,
  totals.screenviews as screen_views,
  totals.uniqueScreenviews as unique_screen_views,
  totals.timeOnScreen as time_on_screen,
  totals.totalTransactionRevenue as total_transaction_revenue,
  totals.sessionQualityDim as session_quality_dim,
  trafficSource.referralPath as referral_path,
  trafficSource.campaign as campaign,
  trafficSource.source as source,
  trafficSource.medium as medium,
  trafficSource.keyword as keyword,
  trafficSource.adContent as ad_content,
  trafficSource.adwordsClickInfo.campaignId as campaign_id,
  trafficSource.adwordsClickInfo.adGroupId as ad_group_id,
  trafficSource.adwordsClickInfo.creativeId as creative_id,
  trafficSource.adwordsClickInfo.criteriaId as criteria_id,
  trafficSource.adwordsClickInfo.page as page,
  trafficSource.adwordsClickInfo.slot as slot,
  trafficSource.adwordsClickInfo.criteriaParameters as criteria_parameters,
  trafficSource.adwordsClickInfo.gclId as gcl_id,
  trafficSource.adwordsClickInfo.customerId as customer_id,
  trafficSource.adwordsClickInfo.adNetworkType as ad_network_type,
  trafficSource.adwordsClickInfo.targetingCriteria.boomUserlistId as boom_user_list_id,
  trafficSource.adwordsClickInfo.isVideoAd as is_video_ad,
  trafficSource.isTrueDirect as is_true_direct,
  trafficSource.campaignCode as campaign_code,
  device.browser as browser,
  device.browserVersion as browser_version,
  device.browserSize as browser_size,
  device.operatingSystem as os,
  device.operatingSystemVersion as os_version,
  device.isMobile as is_mobile,
  device.mobileDeviceBranding as mobile_device_branding,
  device.mobileDeviceModel as mobile_device_model,
  device.mobileInputSelector as mobile_input_selector,
  device.mobileDeviceInfo as mobile_device_info,
  device.mobileDeviceMarketingName as mobile_device_marketing_name,
  device.flashVersion as flash_version,
  device.javaEnabled as is_java_enabled,
  device.language as language,
  device.screenColors as screen_colors,
  device.screenResolution as screen_resolution,
  device.deviceCategory as device_category,
  fullVisitorId as full_visitor_id,
  userId as user_id,
  case channelGrouping
    when '(Other)' then 'Other Source'
    else channelGrouping
  end as channel_grouping,
  socialEngagementType as social_engagement_type
FROM
  {{ source('google_analytics', 'ga_sessions') }}
